services:
  - type: web
    name: predictsite
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn predictsite.wsgi
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        value: python
      - key: ALLOWED_HOSTS
        value: predictsite.onrender.com
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
