services:
  - type: web
    name: rainfall-prediction
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn predictsite.wsgi:application"
    envVars:
      - key:  PYTHON_VERSION
        value: 3.11.8 
